src/main/resources/Diagram/DiagramViewSheet.xml

In order to stop links normalizing to XWiki 2.1 syntax.

Pages created by the Diagram app should use the plain syntax

---

src/main/resources/Diagram/MigrationScript.xml
src/main/resources/Diagram/MigrationScriptLiveTableResults.xml
src/main/resources/Diagram/MigrationScriptMacros.xml
src/main/resources/Diagram/WebHome.xml

Here's a migration script that will replace the old draw.io version to the one installed in the current wiki. Will work only for the pro version (the pro extension id is currently hard coded in the script).

#18: Create a migration script for diagrams affected by #11

---

src/main/resources/Diagram/DiagramEditSheet.xml

Workaround for solve non updated content of the diagram before saving the page.
The link to a Diagram text is not saved in view mode if you don't click outside the text element before saving the Diagram page #37

#37: The link to a Diagram text is not saved in view mode if you don't click outside the text element before saving the Diagram page

---

src/main/resources/Diagram/DiagramEditSheet.xml

When the user selects an image, it will be uploaded as attachment & will be used as URL for the image.
Also, it's a fix for #9.

Store images as attachment #33

---

src/main/resources/Diagram/DiagramEditSheet.xml

* for not having too many versions, upload the attachment only after the delete of the existing one is finished, even if it was succeeded or not.
* an error could appear in the developer console if the attachment does not exists on the page, without altering the functionalities. From the client side you cannot check the existence of the attachment in a different way.

Saving the diagram takes to long after several changes made #49

---

src/main/resources/Diagram/DiagramTranslations.fr.xml
src/main/resources/Diagram/DiagramTranslations.xml
src/main/resources/Diagram/MigrationScript.xml
src/main/resources/Diagram/MigrationScriptLiveTableResults.xml
src/main/resources/Diagram/MigrationScriptMacros.xml
src/main/resources/Diagram/WebHome.xml

- Move the migration script call to a block executed only if there is a valid license
- Move the migration macro call to Diagram.WebHome so that Diagram.MigrationScriptMacros contains macro definition only
- Change slightly the formatting

#34: Migration script: execute only if there is a valid license

---

src/main/resources/Diagram/DiagramEditSheet.xml

Seems like in #46 we overrided the callback function without making checkings for a null value (which is used when importing files from the device).

Issue #33:  Store images as attachment

---

src/main/resources/Diagram/DiagramEditSheet.xml

Issue#55: The link generated by export as URL doesn't contain '//' after protocol

---

src/main/resources/Diagram/DiagramEditSheet.xml

Hide the `browser` option from `Import from` sub-menu since an option for exporting a diagram to the browser doesn't exist.

Issue #26: Can't import a diagram from browser

---

src/main/resources/Diagram/DiagramSheet.xml

As @mflorea suggested in [a2812f4](https://github.com/xwikisas/application-diagram/commit/a2812f41087e600ac4ba79bad63489136cec1d42#r35051870), I added a try/catch block for the code that is responsible for decompressing/decoding a diagram.

Added try/catch block for decoding/decompressing a diagram

---

src/main/resources/Diagram/DiagramEditSheet.xml
src/main/resources/Diagram/DiagramSheet.xml
src/main/resources/Diagram/DiagramViewSheet.xml

* removes from the graph and the cached svg the information about draw.io at save action and adds it back only for view mode, export as pdf (when there is no attachment and the svg is used) and also when entering in edit mode

Paths to images inserted into diagrams become invalid at upgrade #11

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* first version for basic text shapes inserted: simple short text, headings, lists (without their corresponding numbers or bullets), text wrap (not 100% accurate)
* handles recursively the html elements and their children, from inside a foreignObject element; adds specific style (for headings), wraps text (svg 1.0 does not supports it by default), change height if needed (for children elements, where the container is manually computed)
* on TODO list: add the defined style of an element (ex. text alignment); add style for specific not handled tags (i.e. blockquote), handle included links
This is a comparation between the created diagram and it's XWiki Pdf export.
Created diagram:
Exported diagram:

"Textbox" shape isn't showing in XWiki PDF export #100

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* if a paragraph has partially styled nodes, fallback to display only the text and ignore any bold, links.. elements
* refactoring is added in a separate commit

Partially styled elements from a paragraph are not correctly shown in XWiki PDF export #113

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* toBlob is not working in out case for IE
* this issue is related to #59 and as is explained here the diagram cannot be saved as an image attachment in IE; this comment gives more details https://github.com/xwikisas/application-diagram/issues/59#issuecomment-532119659

No PNG or SVG is created while Saving a Diagram on IE 11 #135

---

application-diagram-api/src/main/java/com/xwiki/diagram/internal/handlers/DiagramLinkHandler.java
application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* treated separately the cases of partially styled elements and provide fallback to multiple such cases
* error was raised in java while parsing link+text nodes
Comparison on what the diagram shows:
and what is on the XWiki PDF Export :

The content in the "Text" shape isn't showing in XWiki PDF export when there is text separated on different rows by Enter #118

---

application-diagram-api/src/main/java/com/xwiki/diagram/internal/DiagramLinksRunnable.java
application-diagram-api/src/main/java/com/xwiki/diagram/internal/PageRenameListener.java

* static variable of abstract class was duplicated in child class
* changed logger method that was showing the message only on debug mode
* incorrect style on a page

Diagram installation remains on hold on a XWiki Cloud instance #148

---

application-diagram-ui/src/main/resources/Diagram/DiagramConfig.xml
application-diagram-ui/src/main/resources/Diagram/DiagramConfigClass.xml
application-diagram-ui/src/main/resources/Diagram/DiagramConfigSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramTranslations.xml

* add a property for disabling these features in DiagramConfig and based on this stop the export of pdf from diagram editor or png / jpeg export for IE
* consider that these export could be done from 2 places ( File -> Export As -> Advanced.. and File -> Export As)
External Services Dialog:

Add support for disabling the features that require an external server #105

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* there are shape that don't have a rect as a parent, that is needed as a frame for the wrapping process, and in this case we use the initial width of the mxText node
* rename rectWidth to containerWidth to be more accurate

Can't save diagrams with text inside certain shapes #144

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
application-diagram-ui/src/main/resources/Diagram/ResourceSelector/WebHome.xml

* wait for the modal to be closed before adding the link since in IE 'createLink' is not working if the text is not visible
* in IE we need to set xlink:href of the svg element with namespace

Can't add links in IE 11 #137

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* when multiple styles are added to an element, traverse all children and keep the styles to just one element
* change for partially styled elements also, since this case is treated differently
* identify partially styled elements even if they are not first level children; use these elements when converting them to svg instead of the root element and add needed styles at the end
* treat 'a' and 'li' cases differently since for them a container is returned instead of the given alt
* move functionality to method since it is used in 2 places;
Editor:
PDF Export:

Adding multiple styles to a text element breaks the text display in XWiki PDF Export #153

---

application-diagram-api/src/main/java/com/xwiki/diagram/internal/handlers/DiagramLinkHandler.java
application-diagram-api/src/main/java/com/xwiki/diagram/internal/handlers/GetDiagramLinksHandler.java

* consider that multiple links could be in the same text element

Updating links after renaming a page only works for the first link when the text is separated by "Enter" #151

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* prevent adjusting coordinates multiple times
* modified helper methods to consider also undefined or text nodes that would fallback the element to the basic draw.io converter

Text position is changed in XWiki PDF Export #163

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramSheet.xml
pom.xml

* upgrade dependency
* we don't need to change the '.min' extension manually since the new webjar contains also the map for the minified files, so the unminifying process is done automatically by the browser
* fix the start step by disabling the checkDrafts option, since a pop-up appeared for opening the file in a new window
* rough library is needed for some shapes from the sidebar
* loadUrl was moved from EditorUi; changed it to make import from URL to work
* hideFooter was removed from the code base
* toggleCompactMode parameter was changed from _forceHide_ to _visible_

Update draw.io to the latest version

---

application-diagram-api/src/main/java/com/xwiki/diagram/internal/DiagramLinksListener.java
application-diagram-api/src/main/java/com/xwiki/diagram/internal/DiagramMacroListener.java
application-diagram-api/src/main/java/com/xwiki/diagram/internal/handlers/DiagramContentHandler.java
application-diagram-api/src/main/java/com/xwiki/diagram/internal/handlers/GetDiagramLinksHandler.java
application-diagram-api/src/main/java/com/xwiki/diagram/internal/handlers/StoreHandler.java

* don't add the link if the limit is exceeded
* reset the value of linkedPaged before each diagram parsing, to be sure that it contains only the current document links

Problems with updating diagram content when paths of linked pages exceed 255 characters #193

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* the grapheditor code is used in recent version from drawio, instead of mxgraph; until the new code is added to the webjar,
as a workaround, the missing methods were added

SVG import is not working #199

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramViewSheet.xml
pom.xml

* updated paths to the new grapheditor, graphviewer and mxClient code
* update path to grapheditor images
* load mxClient stylesheet, for editor and viewer, since in the new added code the basePath is not considered
A problem brought by this is that the new mxClient code only has a minified version, being harder to debug now.

Update grapheditor code #201

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* consider the basePath for the shapes added in the left panel

Some shapes aren't visible in the left panel #182 

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* avoid some method calls on mobile since the targeted ui elements are not present on that view mode
* the same is done on drawio https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/diagramly/App.js#L6750

Errors after creating and when trying to save diagrams on mobile #210

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramViewSheet.xml

* make sure that the version loaded with RequireJS (e.g. [here](https://github.com/xwikisas/application-diagram/blob/master/application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml#L1710)) is not a cached one ; for this, `Diagram.DiagramSheet` is loaded first using `$xwiki.jsx.use` in order to use the fix from https://jira.xwiki.org/browse/XWIKI-12981

Caching problems after version upgrade #238

---

application-diagram-ui/src/main/resources/Diagram/DiagramImporter.xml

* the import file request structure changed starting with drawio 20.5.0

Can't import a Gliffy diagram #243

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* Try not to guess the save event button that has been clicked, but instead use the event.target button
* Use stopPropagation instead of preventDefault
Should fix #253

Use the event target button in beforeSave

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

* copied method from a recent version of drawio to include a fix - in the old version of the method, when you import a diagram file on an empty diagram, they would unload the old XWikiFile and use LocalFile, and this breaks a lot of functionalities; this should be removed once we upgrade to a recent version of drawio
* update setData too, since pages are already initialized at that point

Saving imported draw.io file fails #267

---

application-diagram-ui/src/main/resources/Diagram/DiagramMacro.xml

Added the csrf token as a parameter to the diagram creation button.

Warning message when creating a diagram from an existing page using the {{diagram/}} macro #279

---

application-diagram-ui/src/main/resources/Diagram/DiagramMacro.xml

Updated the code to transform the name of the diagram using the current naming strategy.

 The diagram macro doesn't follow the naming strategy when creating a diagram #292

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramSheet.xml

In version 22.0.0, draw.io updated the way it computes the icon path and now it relies on a new global variable called DRAWIO_SERVER_URL, which is based on the current server address. Due to this change, requests intended fordraw.io are mistakenly made locally instead of to the external draw.io server
https://github.com/jgraph/drawio/blame/acd938b1e42cff3be3b629e6239cdec9a9baddcc/src/main/webapp/js/diagramly/Init.js#L51
https://github.com/jgraph/drawio/blame/acd938b1e42cff3be3b629e6239cdec9a9baddcc/src/main/webapp/js/diagramly/Init.js#L25

 Error when clicking several times on More Results #285 

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramSheet.xml

The recent draw.io upgrade broke some CSS across different tabs. This PR should resolve all related issues. I’ve linked all CSS-related issues to this PR so they can be merged in a single update.

 The UI in the "Link..." section appears messed up #287 

---

application-diagram-ui/src/main/resources/Diagram/DiagramSheet.xml

The issue was caused by a mix of different encodings within the same text. For example, when exporting a diagram, Draw.io generates the following URL:
```
https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=TestDiagram.drawio#R%3Cmxfile%3E%3Cdiagram%20id%3D%22C5RBs43oDa-KdzZeNtuy%22%20name%3D%22Page-1%22%3E7VnbcpswEP0aT5%2FaEcgG8hg7cdLWzaRN2kwfBYhLLRAVwpd%2BfRcjDATqS1s7TiY8ZLTLenU5R7tnSA%2BPosWVIEnwibuU9XTkLnr4oqfrlnEGf3PHsnCYpl44fBG6hUurHHfhL6qcSHmz0KVpI1ByzmSYNJ0Oj2PqyIaPCMHnzTCPs%2BasCfFpy3HnENb2PoSuDNS2dLPyX9PQD8qZtXLDESGbLAAaNSRSy%2FLyuKZtRGTqkow0RFvow74UDcFPRTR6YMox9sIzKul%2BRFepvqz25A2q5%2Fa72ZOk2Ng7ansxme1rb9f6EOvqTdaj%2BZLZYcAt4F2DriK0YcRqqwrUQMrFK2VQb8HTBeT5AqI8OCCfWH8F59tRyw9qlQTzr8n90tVFW8u1yQ9uxRSj2oHcYngaBTl%2BBnO2kZ18lyGEYpr8 …
```

 Diagram is not shown when importing from URL #320

---

application-diagram-ui/src/main/resources/Diagram/DiagramMacro.xml
application-diagram-ui/src/main/resources/Diagram/DiagramViewSheet.xml

To resolve this issue properly, I had to address both the diagram macro and the normal diagram page. In the case of the diagram macro, the fix was pretty straightforward: replacing the view of the diagram from a div to the actual SVG. I had to keep the div to avoid errors in the console when exporting the PDF. To make the diagram macro work, we had to do the same thing, in addition I also had to get the right document.

 XWiki export doesn't work properly when a diagram is present. #311

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramTranslations.xml

Renamed 'Export as PDF' to 'Print / Export as PDF' to clarify that the button has two functions. Added an additional title to help users understand how to use the button. More details are available in #321.

Replace drawio PDF export with drawio File -> Print action #288

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml

This issue appears to be more nuanced because there are multiple ways to add links to a page, and there are different types of links. You can add a link directly by selecting the plus button, choosing either "internal" or "external," and adding it or by highlighting text and inserting the link.
Regarding the types of links there are three categories:
1. Custom: These are internal links within XWiki.
2. External (prefixed): These links are prefixed with https://domain and work correctly, redirecting to the external site.
3. External (non-prefixed): These links lack an https:// prefix. Instead of redirecting to the external site, they redirect to localdomain/externalLink.
From my understanding, the behavior of  external (non-prefixed): is not a bug but the intended design of drawio, as it …

 Downloading SVG makes links non functional #319

---

application-diagram-api/src/main/java/com/xwiki/diagram/internal/handlers/DiagramLinkHandler.java
application-diagram-api/src/main/java/com/xwiki/diagram/internal/handlers/GetDiagramLinksHandler.java

This issue occurred because Draw.io has multiple ways of storing links, and our code didn't check for a specific case. To fix it, I updated the methods that retrieve&updates the links from the diagram.
https://github.com/user-attachments/assets/ba0d74b5-ae3d-4e70-bf7c-dfd97ce849ec

 Links in the diagram aren't updated when the linked pages are moved/renamed #245

---

application-diagram-ui/src/main/resources/Diagram/DiagramMacro.xml
application-diagram-ui/src/main/resources/Diagram/DiagramViewSheet.xml

Updated the code to re-execute the loading of the diagram "viewer" when exiting inline edit mode.

Diagram links not showing until page is refreshed, after editing a page with a diagram macro #269

---

application-diagram-api/src/test/java/com/xwiki/diagram/internal/rest/DiagramResourcesImplTest.java

* Unit tests for the code that was added in https://github.com/xwikisas/application-diagram/pull/327

Diagram saves only the current page in attachments when multiple pages are used #261

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramSheet.xml

* The URL export is failing because mxIsElectron is no longer defined. I manually set it to always be false since XWiki is a web app, and Electron is for desktop applications.

Export as "URL...." isn't working and gives "Unknown error" #337

---

application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
application-diagram-ui/src/main/resources/Diagram/DiagramSheet.xml

* The issue was caused by the popup size. I updated the size to be slightly larger to work better with the xwiki ui. However, I couldn't achieve this fully through CSS because drawio has one big class for all the popups adjusts the size through the dialog class, so I had to overwrite the showBackgroundImageDialog

Background "Change..." UI isn't aligned properly #336
